### ISSUE TITLE
The slack channel URL does not work

### ISSUE THREAD

**Issue by maaren** [HASecuritySolutions/VulnWhisperer#100]
When I click on the Join our slack channel URL I get:

This invite link is no longer active.
Please check with the person who shared it with you to see if there's a new link available.

**Comment by maaren** [comment]
Hi @qmontal,

That's fine.

**Comment by reactor7171** [comment]
Hi @maaren ,
I got Slack admin and updated the project link, can you test it out? 
Cheers

**Comment by maaren** [comment]
Hi @qmontal,

It works now!

Thanks

**Comment by ajosh0504** [comment]
Hello! Getting the same message when I click to join the Slack channel! Could someone please add me?
