### ISSUE TITLE
Ingest Nessus Generated CSV from local path vice from Server

### ISSUE THREAD

**Issue by ss10113** [HASecuritySolutions/VulnWhisperer#101]
is there a VulnWhisperer capability to ingest NESSUS-generated CSV from local path?  I don't have the option to connect to the server directly. 

I'm not a coding genius, but I tried adding a "read_path"....no success.

**Comment by reactor7171** [comment]
Hi @ss10113,

As far as I am seeing, the CSV export from Nessus is the one being used by VulnWhisperer locally (at least is exactly the same structure). 

I have NOT tried it myself, but VulnWhisperer does detect if a Nessus file is already downloaded/existing in the filepath (which would be ".../data/nessus/My Scans/scan.csv") and if the entry on the local database is not existing it would update it to reflect that file; that said, you could try to place locally the file in that path and see if it works :)

At the moment we don't have implemented a way to parse files downloaded manually, but we are looking forward having that feature integrated to VulnWhisperer in the future :)

Cheers!

**Comment by elvarb** [comment]
Similar situation with Qualys, being able to read CSV or XML outputs from the scans would also mean you could have multiple contained vulnwhisperer setups regardless of how your scanning processes is.

**Comment by reactor7171** [comment]
I am going to close both #42, #117 and #101 in pro of #64, as all of them are related to the ingestion of XML output files, and ingesting the Nessus XML file will fix both of those issues.
