### ISSUE TITLE
OpenVAS - ERROR: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by Jrcnp** [HASecuritySolutions/VulnWhisperer#123]
### The problem:

After following the existent instructions for vulnwhisperer configurations when running:
`vuln_whisperer -c configs/frameworks_example.ini -s openvas
`
### The output recieved is:

`
INFO:main:Running vulnwhisperer for section openvas
INFO:vulnWhispererBase:Connected to database at /opt/VulnWhisperer/data/database/report_tracker.db
ERROR:main:('Connection aborted.', BadStatusLine("''",))
ERROR: ('Connection aborted.', BadStatusLine("''",))`

### Environment settings:
When using openvas checking-setup in openvas there aren't any bugs. I also dont have any problem regarding executing scans through the cli.

This is a openvas instalation as standalone, not within alienvault.

**Comment by kashif74** [comment]
I had similar issue and found that gsad was listening on port 9392 and not on default port 4000. So check gsad port
netstat -plant | grep gsad
and then change port number in frameworks_example.ini file.

**Comment by reactor7171** [comment]
Hey guys, I have tested the OpenVAS module and it has been working like charm. Also, we have been reported on the Slack channel about other cases that had this same issue, and were actually related to the setup of the users. 
I am going to close this issue, in case someone continues having issues, please create a new one will all the information and debug trail for further checking.
