### ISSUE TITLE
Trying to go to ELK 6.5 (Problem with Gauges)

### ISSUE THREAD

**Issue by cybergoof** [HASecuritySolutions/VulnWhisperer#126]
I'm trying to install VulnWhisperer on ELK 6.5, and having trouble with the kibana boards.  Can you show me a picture of the Risk level Gauges, or describe them?    I can not get them to load, so have to recreate from scratch. 

I'm guessing that the gauges are showing a progress between numbers, but not sure what that should be.

Thanks

**Comment by cybergoof** [comment]
After doing some thinking, I believe that the guages were showing a total amount (filtered by Risk Level), than just having a boring number?

BTW, I am running VulnWhisperer with a full 6.5 version of ELK.  Including fixes to the kibana boards.  Let me know if you would like a pull request.  I'm guessing it will have to be in separate directory like vuln_whisp_kibana_v6

**Comment by reactor7171** [comment]
Hi @cybergoof,
Nice! Migrating to ELK 6.5 is something that was in our backlog and @uovobw was working on with the ansible deployment, we could try to merge it. It would be great to have a PR, although eventually we would prefer to just have support for the 6.x ELK version, this is something that should be agreed as well with @austin-taylor :)

**Comment by cybergoof** [comment]
I have it running in production now.    I got all the visualizations working.  I'll try and export and do a pull request today.   

Do you have test data that you are testing the ingests and dashboards against?

**Comment by homa1978** [comment]
hi cybergoof

I am very interesting and long waiting to use vulnwhisperer in ELK 6.x. Can you share your kibana dashboards and es templates and perhabs a short guide to install.

Thanks

**Comment by cybergoof** [comment]
Yeah, I'm going to try and export.  I need to get a clean version of VulnWhisperer running that isn't tied to our production, so I can test it all out.

**Comment by cybergoof** [comment]
Ugh.  The risk mitigation dashboard is not correct.  I will work on that now.
