### ISSUE TITLE
Question: Multiple Nessus servers

### ISSUE THREAD

**Issue by cybergoof** [HASecuritySolutions/VulnWhisperer#129]
We have multiple nessus servers that we are pulling scans from.   They are all sharing the same database (I run VulnWhisper against each server in a separate docker container that uses the same database file).  

When I ran it the first time against my first server, I got alot of data going back months. But when I ran it against the subsequent servers, I was only picking up todays scans.

What tells VulnWhisper that it has already processed a scan?  Is it SCAN ID and date?

**Comment by reactor7171** [comment]
Hi @cybergoof,
That part of the code should be [here](https://github.com/HASecuritySolutions/VulnWhisperer/blob/master/vulnwhisp/vulnwhisp.py#L319) on the nessus side, and the database check to get the already downloaded records is [here](https://github.com/HASecuritySolutions/VulnWhisperer/blob/master/vulnwhisp/vulnwhisp.py#L150). We are getting all the entries by UUID and SCANNER. 

I think the only reason for this to happen is that the different Nessus servers are having the same UUID to the scans made on that same day, even if maybe the results are different. The way VulnWhisperer works, is that for every scan downloaded, a new entry with the basic data of that entry is added to an internal database, and when we run the sync, we check against the database and ignore those scanids that have been previously downloaded.

Notice that if you delete the file of the data folder but don't delete the database entry, VulnWhisperer will still ignore that entry and will not pull it again; this is something that would be good to check in the future (it does work the other way around though, if file exists but its not in database, vulnwhisperer will add the entry and not download again the data).

**Comment by cybergoof** [comment]
What I ended up doing is creating a different directory for each of the nessus servers and then running the container against each of them.  So it worked out.  A bit clunky for multiple databases, but I think works better as nessus servers come online


closing, thanks for the info.
