### ISSUE TITLE
Validate that Dockerfile works and update documentation

### ISSUE THREAD

**Issue by cybergoof** [HASecuritySolutions/VulnWhisperer#134]
Ensure that the Dockerfile works, and that the latest docker image is being built properly.  When it is, update the README.md

@qmontal  PLEASE ASSIGN TO ME.

**Comment by reactor7171** [comment]
Thanks :)

**Comment by cybergoof** [comment]
I have been off and haven't been able to work on this.  I'm testing it now, seems to work.  Going to get other things in place, and then update the documentation one more time
