### ISSUE TITLE
Build version 6.5 of the docker-compose file

### ISSUE THREAD

**Issue by cybergoof** [HASecuritySolutions/VulnWhisperer#135]
Implement a version 6.5 of the Docker-compose files

You can assign to @cybergoof if you want.

**Comment by homa1978** [comment]
HI !

Is there already a working version of vulnwhisper for ELK 6.x

Br
Mario

**Comment by cybergoof** [comment]
The ELK configurations that are part of the VulnWhipserer project are not at 6.x.  But, if you  have an ELK stack running, then you only need to change the kibana templates.  

they can be found here https://github.com/HASecuritySolutions/VulnWhisperer/tree/master/kibana/vuln_whisp_kibana_6

Let us know if these don't wokr

**Comment by cybergoof** [comment]
@qmontal  and @austin-taylor , I was thinking about how going from 5.6 to 6.x can be a big problematic in terms of versioning.

I was thinking about creating a 'docker-compose.6.yml' file.   And, then create an elk6 directory which will house the ELK configuration files.  Does that sound appropriate?

**Comment by austin-taylor** [comment]
Sounds good to me @cybergoof. We could also just cut a release, but I like the idea of just having folders for now

**Comment by cybergoof** [comment]
Well, i guess the question is, do we want to maintain two versions? (5.x and 6.x)?  or just move to the 6.x?

**Comment by reactor7171** [comment]
Hey guys, as mentioned on the slack channel, I also think it is a good idea to create the "docker-compose.6.yml" file, but I would not maintain the two versions; I would for now keep the files as @cybergoof mentioned of both versions in separate folders while we do the transition, but ultimately I would go for just supporting the latest version of ELK. 

I think we should focus first on making VulnWhisperer failproof to users and solving existent known bugs before supporting different versions of ELK.

**Comment by cybergoof** [comment]
When I went from ELK 5 to 6, there was no breaking changes I could tell.  I don't know if it came in version 6, but logstash will clean up files after it has been pushed to Elasticsearch.  So that is good.

I'll put this together this weekend.
