### ISSUE TITLE
error message getting logs from openvas

### ISSUE THREAD

**Issue by xxoc77** [HASecuritySolutions/VulnWhisperer#137]
Hi,
I get the following messages running:
vuln_whisperer -c configs/frameworks_example.ini -s openvas
INFO:main:Running vulnwhisperer for section openvas
INFO:vulnWhispererBase:Connected to database at /opt/VulnWhisperer/data/database/report_tracker.db
INFO:OpenVAS_API:Retreiving OpenVAS report data...
ERROR:main:local variable 'report' referenced before assignment
ERROR: local variable 'report' referenced before assignment

Can someone please tell me which variable it is referencing to?

**Comment by reactor7171** [comment]
Hi @xxoc77,

Did you find out what was the issue? If so, would you mind sharing in the Issue so that other users that find the same issue can solve it as well, and for use to solve the bug for future releases?

Cheers!

**Comment by justin-p** [comment]
Just wanna chime in here. This error also occurs if there are no reports in OpenVAS to pull from.
Took me longer to realize this was the issue than I care to admit. 😄
