### ISSUE TITLE
How many servers are supported by scan?

### ISSUE THREAD

**Issue by leomatias** [HASecuritySolutions/VulnWhisperer#140]
Hello VulnWisperer Team!

                            I have 350 servers in my scan, I have to manually delete servers until I reach 100, then run vulnwhisperer. Then again, delete 100 servers and run it again until i have reached 350... 

                             Is there any difference if I export to CSV from Nessus console and then add it to ELK? What would be the difference between this .csv file and the .csv file generated by VulnWhisperer?

Thanks and regards.-

DEBUG:NessusAPI:Found 1 scan_ids
INFO:vulnWhispererNessus:Connected to nessus on 192.168.220.131:8834
DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans
INFO:vulnWhispererNessus:Gathering all scan data... this may take a while...
DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10
DEBUG:NessusAPI:Converted timestamp 2019-01-06 00:07:20 in datetime 1546754840
INFO:vulnWhispererNessus:Identified 1 scans to be processed
INFO:vulnWhispererNessus:Directory already exist for /opt/VulnWhisperer/data/nessus/My Scans - Skipping creation
DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10
DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export?history_id=24
INFO:NessusAPI:Download for file id 1816162998
DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/10/export/1816162998/status
.INFO:NessusAPI:Done: 36
DEBUG:NessusAPI:Requesting to url https://192.168.220.131:8834/scans/exports/0dea8be513d52ea3295e58b7d80463710811194fc00347aba1d5a9b44d482075/download
DEBUG:NessusAPI:Returning data.content
ERROR:main:

**Comment by reactor7171** [comment]
Hi @leomatias,
Sorry for the inconvenience, I would have not imagined that there were these kind of limitations when connecting to the scanners. Unfortunately, currently we don't support processing direct exports in VulnWhisperer, and yes, there is a difference between the original CSV Nessus file and the VulnWhisperer one. 

We are working on several things at the time but we are lacking a bit of resources, so I couldn't tell you when either the bug you mentioned or the direct import of CSV files would be implemented; although when the time comes, I would ask you if it would be possible to work together in the bug, as you are the first and only instance that came across this issue.

Cheers!

**Comment by reactor7171** [comment]
Hey @leomatias,

I am afraid I am going to need more information about this "bug", as now that I checked with my own instance, I am having ~300 hosts, numbers changing weekly, and VulnWhisperer pulls as expected all the hosts at once, and I have all the data in our ELK instance. 

I have been using Nessus v6 and have now migrated to v8 due to Nessus deprecation of v6 and v7, and still don't see any issue for now.

Thanks ^^

**Comment by reactor7171** [comment]
This is also would not be possible taking into account that we have had issues in #63 due to having over 1000 hosts and being the results to big for the request to handle it...
