### ISSUE TITLE
[Logstash] Errors on logstash config file processing

### ISSUE THREAD

**Issue by reactor7171** [HASecuritySolutions/VulnWhisperer#148]
**Describe the bug**
Two issues appear with Logstash when trying to index events in elasticsearch:

`logstash         | [2019-02-11T10:38:59,923][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-vulnwhisperer-2019.02", :_type=>"doc", :routing=>nil}, #<LogStash::Event:0x550535e4>], :response=>{"index"=>{"_index"=>"logstash-vulnwhisperer-2019.02", "_type"=>"doc", "_id"=>"mI4j3GgBwVRx2Qp2fOPx", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [vendor_reference] of type [date]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"Invalid format: \"cisco-sa-20170317-cmp\""}}}}}`

`logstash         | [2019-02-11T10:39:29,507][INFO ][filewatch.readmode.handlers.readfile] buffer_extract: a delimiter can't be found in current chunk, maybe there are no more delimiters or the delimiter is incorrect or the text before the delimiter, a 'line', is very large, if this message is logged often try increasing the `file_chunk_size` setting. {"delimiter"=>"\n", "read_position"=>11763712, "bytes_read_count"=>32768, "last_known_file_size"=>13555800, "file_path"=>"/opt/vulnwhisperer/data/qualys/qualys_vuln_scan_1548792380.58339_1548792378.json"}`

**Affected module**
Logstash

**To Reproduce**
1. Deploy docker-compose setup
2. Wait to have scanner data downloaded
3. Allow logstash to process the results

**Expected behavior**
No issues should appear

**Screenshots**

**System in which VulnWhisperer runs (please complete the following information):**
 - OS: Ubuntu Server
 - Version: 18.04 LTS

**Comment by pemontto** [comment]
This looks like it was caused by dynamic mapping. We have now explicitly defined vendor_reference in the template as a keyword so this should no longer occur.
https://github.com/HASecuritySolutions/VulnWhisperer/blob/60c56b778e7432e12901b8a9426cded3eb4cccbd/resources/elk6/logstash-vulnwhisperer-template.json#L224-L226
