### ISSUE TITLE
[ELK 6 -KIbana.json] -  Overrides the default logstash index

### ISSUE THREAD

**Issue by HKcyberstark** [HASecuritySolutions/VulnWhisperer#157]
**Describe the bug**
To Summarize

I created an index logstash-vulnwhisperer-* to see logs into my kibana.  I am able to see the parsed fields in discover tab. Great !

Next - I imported the kibana.json from ELK6 folder in github into my kibana - saved objects. 
This asks me if I need to overwrite logstash-vulnwhisperer-* index.  so I accepted and dashboards are created..

Now -  dashboards are available but data will not be injected and with no data. 
Discover tab - logstash-vulnwhisperer-*  index which i created initially doesn't have data now.  It says no object.  

now if I try to delete the logstash-vulnwhisperer-* index and recreate it   -  data is back in discover but dashboards get broken.

**Affected module**
Kibana Dashboard and Indexing

**To Reproduce**
1. Index the openVAS scan logs using default index name  logstash-vulnwhisperer-*
2. Import Kbana.json available in ELK6 folder of github repo into your kibana saved objects

**Expected behavior**
Dashboard to be Compatible with Default Index created from logstash-vulnwhisperer-*  

**Screenshots**
I dont have screenshots at the moment. let me know if it is necessary, I can reproduce the issue and provide screenshots. 

**System in which VulnWhisperer runs (please complete the following information):**
 - OS: CentOS 7 
VM 1 - openVAS and Vulnwhisperer configured.
 VM 2 - ELK 6.6.2 -  ELK is a standalone and not using Docker. 

Thanks in Advance . Appreciate your kind help.

**Comment by tylerwebb30** [comment]
Add the following to your logstash file it will fix this issue. 
     mutate { 
	convert => {
	  "plugin_id" => "integer"
          "cvss" => "float"}
    }

**Comment by reactor7171** [comment]
The fix has been implemented in the `beta-1.8` branch, although not yet integrated with the master branch; the fix was initially done only to ELK5 template in #163 , as well as to ELK6 in #174.

Will need to wait until the release of `VulnWhisperer 1.8` for having it in the `master` branch, meanwhile you can get the file from the `beta-1.8` one.

**Comment by reactor7171** [comment]
Finally decided to change it to a `keyword` field, this solves previous issues and allows it to be searchable.
