### ISSUE TITLE
openvas pull failed

### ISSUE THREAD

**Issue by WazuhUser** [HASecuritySolutions/VulnWhisperer#173]
Hi,

I've installed an Ubuntu 18.04 server and then Vulnwhisperer in it. In another machine I have an openVas with some scans, and I want to pull this info from Vulnwhisperer. 

I've run the next command: 
vuln_whisperer -c configs/frameworks_example.init -s openvas 
![image](https://user-images.githubusercontent.com/45871592/56036200-87cfd680-5d2c-11e9-9acd-bc1418f531e9.png)

And i get the next error: 
The frameworks conf file is the next: 
![VulError](https://user-images.githubusercontent.com/45871592/56033048-f0ff1c00-5d23-11e9-8c3e-c670c4b72974.PNG)
 
How could I fix it?

Thanks!!

**Comment by reactor7171** [comment]
That specific error is regarding the `requests` library not existing in the system, have you installed with pip the libraries from `requirements.txt` as mentioned on the instructions?

Also, it would be better for you to use the beta-1.8 version of vulnwhisperer (you can do after git clone `git checkout beta-1.8 ` to change to that branch), as it has some fixes that would affect you over the master branch.

Cheers!

**Comment by reactor7171** [comment]
Closing issue, as it should be already solved after installing the dependencies.
