### ISSUE TITLE
Can´t pull openvas reports

### ISSUE THREAD

**Issue by WazuhUser** [HASecuritySolutions/VulnWhisperer#189]
Hi,

I'm trying to pull data from my openvas to vlnwhisperer but I get the next error: 

![image](https://user-images.githubusercontent.com/45871592/65869500-de80a980-e37a-11e9-9418-a106b5b4a948.png)

The test.ini conf is the next one:

![image](https://user-images.githubusercontent.com/45871592/65869564-fc4e0e80-e37a-11e9-9585-44261e78deb0.png)

Our company is trying to use vulnwhisperer so, please help us with some information.
Thank you

**Comment by reactor7171** [comment]
Hi @donetz8,

It looks like if you don't have installed the pytz library, have you installed the libraries from the requirements.txt file as mentioned here? https://github.com/HASecuritySolutions/VulnWhisperer#requirements

Cheers

**Comment by WazuhUser** [comment]
Hi qmontal, 

You were right,  it was that!! I thought it was installed but it's not. I'll keep trying to see reports in elk,

Thanks!

**Comment by WazuhUser** [comment]
Hi, 

I've obtained to see reports in Kibana, each document is presented in  discover. The index is created for September and October, but when I create a wildcard index (logstash-vulnwhisperer-*) I can´t see nothing in discover. Why could it be? Should I use the template in addition of openvas.conf file?

**Comment by reactor7171** [comment]
Hi @donetz8,

The template and the openvas.conf files have different purposes: the conf file is for the Logstash log parsing configuration, while the template is the one having the Kibana indexes and objects to visualize the data. 

In the [FAQ](https://github.com/HASecuritySolutions/VulnWhisperer/wiki) there is a solution to an index error, `Elasticsearch index not found: logstash-vulnwhisperer`, but I believe this is not the problem that you are encountering.

Cheers

**Comment by reactor7171** [comment]
I will close this issue as the problem why the ticket was raise initially has been solved; if there are other problems, please check if there is any other raised issue for that or create a new ticket for it.

Thanks! :)
