### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by marcelaraujo** [HASecuritySolutions/VulnWhisperer#19]
It will be nice if this project supports Docker deployment.

Tks

**Comment by austin-taylor** [comment]
We're working on this now

**Comment by marcelaraujo** [comment]
Awesome @austin-taylor

**Comment by reactor7171** [comment]
Hi @marcelaraujo,

There is currently both Dockerfile and docker-compose for the VulnWhisperer project. You can check about both at [VulnWhisperer's wiki](https://github.com/austin-taylor/VulnWhisperer/wiki) and the [README.md file](https://github.com/austin-taylor/VulnWhisperer/blob/master/README.md).

If there is any other doubt or problem, don't hesitate to open a new issue :)
