### ISSUE TITLE
Docker build fails with CentOS 8

### ISSUE THREAD

**Issue by scottmcgowan** [HASecuritySolutions/VulnWhisperer#199]
**Describe the bug**
VulnWhisperer Dockerfile pulls centos:latest, which points to CentOS 8 (released Sept 2019).  CentOS 8 does not specify a `python` argument, it specifies `python2` or `python36`.  This causes the VulnWhisperer Docker build to fail.

**Affected module**
Dockerfile

**VulnWhisperer debug trail**
NA

**To Reproduce**
1. Remove any VulnWhisperer Docker containers and images
2. Build Docker image from Dockerfile: `docker build -t vulnwhisperer-local .`
3. On step 3/13 of the build, after `RUN yum update -y` completes, observe output:
`No match for argument: python
There are following alternatives for "python": python2, python36
No match for argument: python-devel
Error: Unable to find a match
The command '/bin/sh -c yum update -y &&     yum install -y python python-devel git gcc &&     curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py &&     python get-pip.py' returned a non-zero code: 1`

**Expected behavior**
The Dockerfile should build without error

**System in which VulnWhisperer runs (please complete the following information):**
 - Tested with Docker CE 19.03.4 on Ubuntu 18.04 and Windows 1809

**Comment by reactor7171** [comment]
Closing as the PR was merged, thanks @scottmcgowan!
