### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by hsninbil** [HASecuritySolutions/VulnWhisperer#204]
**Describe the bug**

**Affected module**
Which one is the module that is not working as expected, e.g. Nessus, Qualys WAS, Qualys VM, OpenVAS, ELK, Jira...). 

**VulnWhisperer debug trail**
If applicable, paste the VulnWhisperer debug trail of the execution for further detail (execute with '-d' flag).

**To Reproduce**

**Expected behavior**

**Screenshots**

**System in which VulnWhisperer runs (please complete the following information):**
 - OS: [e.g. Ubuntu Server]
 - Version: [e.g. 18.04.2 LTS]
 - VulnWhisperer Version: [e.g. 1.7.1]

**Additional context**

## Important Note
As VulnWhisperer relies on ELK for the data aggregation, it is expected that you already have an ELK instance or the knowledge to deploy one. 
In order to speed up deployment, we provide an updated and tested docker-compose file which deploys all the needed infrastructure and we will support its deployment, but we will not be giving support to ELK instances.

**Comment by reactor7171** [comment]
User wrote on #203
