### ISSUE TITLE
Request for clearer installation instructions

### ISSUE THREAD

**Issue by b4cktr4ck2** [HASecuritySolutions/VulnWhisperer#21]
Hi,

I've downloaded the tool and I'm currently in the process of setting it up with Nessus. However, I was running into some issues with Vulnwhisperer not picking up the report_tracker.db file. As it turns out, Nessus needs to create this database file and then the path must be supplied in the Vulnwhisperer configuration file. Could you please update the configuration screenshot to maybe say something like "write_path=/path/to/nessus/report_tracker.db" or something like that? As a new user to Nessus and Vulnwhisperer this took me a while to understand on my own.

I'm also curious what the next steps are with a brand new installation? Once I point Vulnwhisperer to the right database, what comes next? My understanding is that the ELK stack should be started?

**Comment by Vir4Aparicio** [comment]
I'm trying to install in ubuntu, and is imposible with the steps of this guide. My impression is that it is incomplete and many of the necessary steps have been skipped, about how to get to know it with nessus, with the database, etc.
I get the same error as the previous user (1kozlovsas ) comments.

**Comment by austin-taylor** [comment]
I'll post some instructions for setting up ELK tonight. Probably easier if I create a VM.

**Comment by Vir4Aparicio** [comment]
Ok, Thanks!

**Comment by Vir4Aparicio** [comment]
hi @1kozlovsas !

This error is solvented creating a db with sqlite3: 
--> sqlite3 report_tracker.db
/opt/VulnWhisperer/vulnwhisp/database/report_tracker.db   (db path)

-->/opt/VulnWhisperer$ vuln_whisperer -c configs/nessus.ini -s nessus
[INFO] Connected to database at /opt/VulnWhisperer/vulnwhisp/database/report_tracker.db
[INFO] Attempting to connect to nessus...
[SUCCESS] Connected to nessus on virginia-hp-probook-450-g0:8834
[INFO] Gathering all scan data... this may take a while...
[INFO] Identified 1 scans to be processed
Download for file id 1761093580.
Processing 1/1 for scan: Test_scan
[INFO] 55 records written to Test_scan_5_6_1517595240.csv

I hope that help you!

**Comment by austin-taylor** [comment]
Go ahead and touch report_tracker.db for now.  I'll get this updated in code soon.

**Comment by b4cktr4ck2** [comment]
I'll give that a shot, thanks @Vir4Aparicio and @austin-taylor

**Comment by Wyv3rnSec** [comment]
Don't know if this is past the relevance date, but in answering the ELK questions on standing up a new build (Assuming its a standalone node) the install would look like the following:

Elastic 5.x (My personal go-to would be 5.6 for this reference) Pulling this from Elastic.co Docs.

DEB: (https://www.elastic.co/guide/en/elasticsearch/reference/5.6/deb.html)

#If you dont have java on this new box, you will need it
sudo apt-get install -y default-jre

#If you care for the signing key
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

sudo apt-get install apt-transport-https

echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list

#Now comes the install. (Assuming Logstash is on another host)
sudo apt-get update && sudo apt-get install elasticsearch kibana

#Configuration
With a new setup you will need to edit the /etc/elasticsearch/elasticsearch.yml & /etc/kibana/kibana.yml config files to have the same IPs that match your logstash file. They default to localhost which wont work in this setup with multiple machines (well it may but will most likely cause issues).

If you need further help Elastic.co has some great documentation surrounding their tech.

Also debating starting a slack for alot of these InfoSec projects for quicker answers/community help.

**Comment by reactor7171** [comment]
Didn't have any issue following the current deployment Readme instructions, can we consider this issue solved?

**Comment by reactor7171** [comment]
Closing issue as it has been solved and solution has been added to documentation.
