### ISSUE TITLE
Support for OpenVAS

### ISSUE THREAD

**Issue by willemdh** [HASecuritySolutions/VulnWhisperer#24]
Please add support for OpenVAS

**Comment by austin-taylor** [comment]
In progress

**Comment by ghost** [comment]
what is the progress on this? I see you've added an openVAS connector - should we be able to pull in OVAS reports now or is it still in development? Thanks!

**Comment by austin-taylor** [comment]
Still working out the database and a couple other items.  Hoping to have done by next week.  Stay tuned!

**Comment by austin-taylor** [comment]
Please give it a try now.

**Comment by austin-taylor** [comment]
Confirmed Openvas is working for other users. If you have trouble, please open a new ticket.
