### ISSUE TITLE
HeatMap VulnWhisperer - Critical Assets not work

### ISSUE THREAD

**Issue by Vir4Aparicio** [HASecuritySolutions/VulnWhisperer#26]
![image](https://user-images.githubusercontent.com/24496660/36021569-8121f3c8-0d86-11e8-9e5a-52ca5652513f.png)

**Comment by austin-taylor** [comment]
Did you enable them in your logstash file? You need to specify the subnet or hostnames.  Examples are included,  but commented.

**Comment by austin-taylor** [comment]
Closing for now. Please re-open a ticket if you still need assistance.
