### ISSUE TITLE
Unable to create qualys reports - invalid template id

### ISSUE THREAD

**Issue by ghost** [HASecuritySolutions/VulnWhisperer#28]
I am unable to get pass the report generation stage - seems an invalid template ID is being used to generate the qualys reports.

```
Processing 1/399
[ACTION] - Generating report for 10794322
[FAIL] Could not process report ID: <?xml version="1.0" encoding="UTF-8"?>
<ServiceResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://qualysapi.qg2.apps.qualys.com/qps/xsd/3.0/was/report.xsd">
  <responseCode>INVALID_REQUEST</responseCode>
  <responseErrorDetails>
    <errorMessage>Template with id 126024 was not found. Provide a different template id.</errorMessage>
  </responseErrorDetails>
</ServiceResponse>

```
I am unclear where the template id of 126024 is coming from. Anyone else having a similar issue?

**Comment by austin-taylor** [comment]
Hi Matthew, please login to your qualys web app server and look at the available templates you have. There should be a template ID there. Once you find the ID, please update the config.ini file

**Comment by ghost** [comment]
Thanks! I can't believe I overlooked that. That worked great. I've run into a different issue but at least I'm making progress. If I can't figure it out I'll submit another issue. Thanks again.

**Comment by ghost** [comment]
I'm fairly new to infosec but I'd certainly be glad to help - for instance, I ran into a few issues getting set up because my machine has both python 2.7 and 3, so I ended up having to manually install python 2 versions of a few items like panda and lxml. I'm sure someone else will run into that at some point :)
