### ISSUE TITLE
Empty json reports - qualys - unexpected keyword argument 'lines'

### ISSUE THREAD

**Issue by ghost** [HASecuritySolutions/VulnWhisperer#29]
Hello. I am unable to get the json output for my qualys scans.
```
[ACTION] - Generating report for 12206112
[INFO] - Successfully generated report! ID: 12206112
[INFO] - New Report ID: 813288
[ACTION] - File written to /opt/vulnwhisp/qualys/813288.csv
[ACTION] - Downloading file ID: 813288
[FAIL] - Could not process 12206112 - to_json() got an unexpected keyword argument 'lines'
```
The csv reports generate just fine, but not the json - the json files are empty due to the above error. As far as I can tell, the logstash filters for qualys are set up for ingesting the json, not the csv, correct? Can I do anything withe CSV reports that are generated or do they exist only as a step in creating the final json report format?

**Comment by austin-taylor** [comment]
Sounds like you have an outdated version of pandas. Mind doing a pip freeze | grep pandas? You'll need 0.19.0 and higher.

**Comment by ghost** [comment]
Thanks! That solved it.
