### ISSUE TITLE
Fails to Download Scans

### ISSUE THREAD

**Issue by Wyv3rnSec** [HASecuritySolutions/VulnWhisperer#30]
I have setup VulnWhisperer as instructed but when I go to run it authenticates then fails to download the 3 scans identified.

Any way to see more verbose logging of why its failing? 

I thought it could be file permissions issue but turns out it wasn't.

Open to ideas.

![image](https://user-images.githubusercontent.com/32689998/36389149-34125f80-156c-11e8-91dd-657f2b58a343.png)

**Comment by Wyv3rnSec** [comment]
It appears when working with custom Scans the Python errors out when looking for certain fields.

**Comment by austin-taylor** [comment]
Yeah we need to know the fields ahead of time to mold then into a unified dashboard

**Comment by rshrestha6** [comment]
Hi Austin

Could you please elaborate more on "Yeah we need to know the fields ahead of time to mold then into a unified dashboard" if possible.

Thanks
