### ISSUE TITLE
 Could not connect to database at /opt/vulnwhisp/database/report_tracker.db

### ISSUE THREAD

**Issue by rshrestha6** [HASecuritySolutions/VulnWhisperer#32]
I'm attempting to setup Vulnwhisp on a Ubuntu machine and getting the following error "Could not connect to database at /opt/vulnwhisp/database/report_tracker.db", not sure how to get around this problem, can anyone please help??

**Comment by austin-taylor** [comment]
you need to touch report_tracker.db in /opt/vulnwhisp/database 

I'll get a PR in to fix that automatically.

**Comment by Wyv3rnSec** [comment]
In the short term for Austin's fix, you can create the directories and make sure when running the scripts you have the proper file permissions allow you to read/write in that specified directories. 

I have found these are 90% of my overlooked linux issues.

**Comment by rshrestha6** [comment]
thanks for the prompt reply but can u please shed some more light, as touch gives me following error
touch: cannot touch '/opt/vulnwhisp/database': No such file or directory

Am I suppose to create that directory first??

**Comment by austin-taylor** [comment]
Yes, the directory path must exist. Please use mkdir -p /opt/vulnwhisp/database, then touch /opt/vulnwhisp/database/report_tracker.db

**Comment by austin-taylor** [comment]
Issue is fixed in latest PR
https://github.com/austin-taylor/VulnWhisperer/commit/d8e813ff5a21f6fff7604caefc7aed3421ec504c

please do a git pull, reinstall, and try again.
