### ISSUE TITLE
doesnot do anything after "identified scans to be processed

### ISSUE THREAD

**Issue by rshrestha6** [HASecuritySolutions/VulnWhisperer#35]
Hi,
I have managed to get the command working with "touch report_tracker.db", however the scripts runs acknowledges the nessus scan but it doesn't go further than that, not sure what is going on.  Can anyone help?

->/opt/VulnWhisperer$ vuln_whisperer -c configs/nessus.ini -s nessus
[INFO] Connected to database at /opt/VulnWhisperer/vulnwhisp/database/report_tracker.db
[INFO] Attempting to connect to nessus...
[SUCCESS] Connected to nessus on localhost:8834
[INFO] Gathering all scan data... this may take a while...
[INFO] Identified 1 scans to be processed

**Comment by Wyv3rnSec** [comment]
Few questions;
Is this an existing Nessus instance or new build?
Did you import scans?
Is this a custom scan you built out with different headers?

I have had issues when i imported scans as it carves off some metadata that the python is looking for to pull the scans in.

If you run a local Nessus scan say on 1-2 targets then run the script and see if it pulls in your test scan. (Only if new Nessus server)

#30 My issue i opened then saw the flaw in my ways for reference.

**Comment by rshrestha6** [comment]
Thanks.. Yes i imported nessus scans that was done with a different machine. I will try to run a local scan and then try it again.

Appreciate your advise.

**Comment by rshrestha6** [comment]
It seem to process the scan if it is local (although I haven't been successful in indexing it on elastic-search or kibana web interface , will need to work further on that),
However how do i get it to work on imported scans (say if i have a historical nessus scan) ? and also it seems to process the existing scans only once, and once that is processed to .csv file if you run it again it just skips the conversion even if you have deleted the .csv file from "/opt/vulnwhisp/nessus/My Scans "

Can anyone suggest.

Thanks in advance.

**Comment by Wyv3rnSec** [comment]
Answering the second question first, it wont process the scan twice as the reporttracer.db tells the tool that you have already pulled down that scan and not to process it again. If you delete the .db file it should reprocess it. 

As for the imported scans, I haven't had time yet to adjust Austin's Python to pull in these files.

**Comment by rshrestha6** [comment]
Thanks for that .

deleting .db is now giving me some strange error..

root@test-virtual-machine:/home/test/Desktop/VulnWhisperer-master# vuln_whisperer -c configs/frameworks_example.ini -s nessus
[INFO] Connected to database at /opt/vulnwhisp/database/report_tracker.db
[INFO] Attempting to connect to nessus...
[SUCCESS] Connected to nessus on localhost:8834
[INFO] Gathering all scan data... this may take a while...
[INFO] Identified 7 scans to be processed
[INFO] Directory already exist for /opt/vulnwhisp/nessus/My Scans - Skipping creation
Download for file id 435398102.
.
Processing 1/7 for scan: attemptthird
[INFO] 79 records written to attemptthird_19_20_1519954223.csv 
Download for file id 1400422544.
.
Processing 3/7 for scan: attempt 1
[FAIL] ERROR: [Errno 2] No such file or directory: u'/opt/vulnwhisp/nessus/Trash/attempt_1_14_15_1519952202.csv'

**Comment by Wyv3rnSec** [comment]
I read that as its looking for a csv in a trash folder?

Is there a file in your nessus trash?

The .db file i was referring to was /opt/vulnwhisp/database/report_tracker.db

**Comment by rshrestha6** [comment]
strange!! that is what i did, I deleted the .db file from /opt/vulnwhisp/database/ and recreated it again, not sure why it is looking for the trash folder which doesn't even exist?

Also a stupid question does the logstash .conf file has to be in the same directory as logstash ? as I am not seeing anything in elastic-search.  it seems that default location is all different and the instructions from official webpage doesnot seem to work anymore 

for example ruining log-stash with a config 
bin/logstash -f logstash.conf


thanks

**Comment by Wyv3rnSec** [comment]
Each time you run Vulnwhisperer its going to create that .db file if one is not found.

Logstash: Depends on your setup if you are running the files individually via CLI or as a service.

Assumptions:
Logstash.yml is located in /etc/logstash/

For example I can run a individual .conf with the following.

/usr/share/logstash/bin/logstash --path.settings /etc/logstash/ -f /home/testuser/logstash-csv.conf

If you run as a service by starting logstash via systemctl or sudo service logstash start... Then by default it will look in /etc/logstash/confd/ directory for your .conf files.

**Comment by rshrestha6** [comment]
Thanks ..
