### ISSUE TITLE
Check if config file exists, and provide error message

### ISSUE THREAD

**Issue by cybergoof** [HASecuritySolutions/VulnWhisperer#4]
create a different error message if the config ini file does not exist. Current error says "Could not properly load your config!  Reason: No Section: 'nessus'".

Stating that the file did not exist would help with troubleshooting issues.

**Comment by lianfeng30** [comment]
im used Mac
have same error：
Could not properly load your config!
Reason: No section: 'nessus'

**Comment by austin-taylor** [comment]
@lianfeng30 mind sharing a copy of your config? I'll update the error so its more descriptive, but you should have something that looks like: https://github.com/austin-taylor/VulnWhisperer/blob/master/configs/frameworks_example.ini

**Comment by austin-taylor** [comment]
@lianfeng30 what command did you execute to receive the error?

**Comment by lianfeng30** [comment]
@cybergoof 
~ vuln_whisperer
[FAIL] Could not properly load your config!
Reason: No section: 'nessus

**Comment by lianfeng30** [comment]
@cybergoof  my config:
[nessus]
enabled=true
hostname=localhost
port=8834
username=admin
password=admin
write_path=/opt/vulnwhisp/scans
db_path=/opt/vulnwhisp/database
trash=false
verbose=true

ls -l /opt/vulnwhisp/
total 0
drwxr-xr-x  2 test  admin  68 12  7 13:59 database
drwxr-xr-x  2 test  admin  68 12  7 13:59 scans

**Comment by lianfeng30** [comment]
@cybergoof  
Is not i supposed to start the nessus scanner to scan some targets?
And start vuln_whisperer at nessus runtime?

**Comment by lianfeng30** [comment]
vuln_whisperer -c /Users/test/VulnWhisperer_with_nessus/configs/frameworks_example.ini
[INFO] Attempting to connect to nessus...
[SUCCESS] Connected to nessus on localhost:8834
[INFO] Connected to database at /opt/vulnwhisp/database/report_tracker.db
[INFO] Gathering all scan data... this may take a while...
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
'NoneType' object is not iterable
[INFO] Identified 1 scans to be processed

**Comment by austin-taylor** [comment]
Looks like it's working great. I'll fix the NoneType error. That's been on the todo list for a while.

**Comment by austin-taylor** [comment]
I commented out the line causing the print statements @lianfeng30 if you pull the latest version, you shouldn't receive that error anymore.

**Comment by lianfeng30** [comment]
@austin-taylor
OK I am going to update the test now

**Comment by lianfeng30** [comment]
@cybergoof oh ..
It is normal, thanks!

After this how to operate, let the data into kibana?

**Comment by lianfeng30** [comment]
elasticsearch -version
Version: 5.6.3

logstash --version
logstash 5.6.2

kibana
Version: 5.6.3

**Comment by austin-taylor** [comment]
I've been meaning to write a blog on how to install for some time, but you will need to first install the plugins for logstash (swimlane I believe and maybe one other), setup filebeats to monitor a specific directory, update your hostname in the logstash.conf example file that asks for a hostname. You'll want to name it wherever you're shipping from. Then you can import all the visualizations into Kibana. 

I will need to make a step by step instruction blog, but all the execuses...

**Comment by lianfeng30** [comment]
@cybergoof 
thank you very much!
Many people are concerned about this project, are looking forward to your update and your configuration instructions blog

We will continue to pay attention to your information, please write a guide blog as soon as possible, waiting for your update!

Thanks again!
