### ISSUE TITLE
No output when running for openvas

### ISSUE THREAD

**Issue by ghost** [HASecuritySolutions/VulnWhisperer#43]
I've updated vulnwhisp.py, added the openvas section to the config file, and added openvas.py to the frameworks folder. When I run `vuln_whisperer -c configs/frameworks_example.ini -s openvas` there is no output and I am immediately returned to the command prompt.

**Comment by austin-taylor** [comment]
assuming you have updated frameworks_example.ini [openvas] section with your server settings? What did you have to do with vulnwhisp.py?

**Comment by ghost** [comment]
I actually started from scratch over the weekend to make sure I had the latest version of all the code. Qualys runs fine, but the same behavior for openvas is exhibited: no output and I am immediately returned to the command prompt.

**Comment by austin-taylor** [comment]
Okay, i'll add some more logging to it. Could you try running with -v to turn on verbose and see if the error is output. Also, please make sure you have permissions to the directory you're trying to write to.

**Comment by ghost** [comment]
No extra output with the -v flag. As a test, I ran vulnwhisp with the nessus option set (I don't have nessus enabled) to see what output I received. As expected, the output was:
```
ubuntu@sec-data:/opt/vulnwhisp$ sudo vuln_whisperer -v -c configs/config.ini -s nessus
[INFO] Connected to database at /opt/vulnwhisp/database/report_tracker.db
[INFO] Attempting to connect to nessus...
HTTPSConnectionPool(host='localhost', port=8834): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f33b87a2910>: Failed to establish a new connection: [Errno 111] Connection refused',))
[FAIL] Could not properly load your config!
Reason: [FAIL] Could not connect to nessus -- Please verify your settings in <vulnwhisp.base.config.vwConfig object at 0x7f33b8790c90> are correct and try again.
Reason: HTTPSConnectionPool(host='localhost', port=8834): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f33b87a2910>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
I then set openvas to false in the config and ran vulnwhisp and I still get no output at all. Not even a failed to connect.

**Comment by austin-taylor** [comment]
Did you run python setup.py develop after downloading the latest version?

**Comment by ghost** [comment]
I don't believe I did, however I just ran it and the behavior is the same.

**Comment by ghost** [comment]
I think this may have been an issue of missing dependencies, as mentioned in another issue ticket. I have done a fresh install of vulnwhisp and was able to get output, whereas before I was getting nothing at all when running vulnwhisp with the openvas option. I am having other issues, but I will open a new issue ticket to address those.
