### ISSUE TITLE
Token error with Nessus

### ISSUE THREAD

**Issue by webhead404** [HASecuritySolutions/VulnWhisperer#44]
I am able to connect to Nessus per the documentation. However after my scans are identified the next line says 

[ERROR] 'token'

local variable 'token_id' referenced before assignment. 

I am trying to debug as well.

**Comment by webhead404** [comment]
i am running Nessus 6.8.1

**Comment by austin-taylor** [comment]
Underneath this line` req = self.request(query, data=json.dumps(data), method='POST', json=True)`

could you add print `req.content`

then re-install with `python setup.py develop` and run the script again?

**Comment by webhead404** [comment]
This time I got 'dict' object has no attribute 'content'

**Comment by austin-taylor** [comment]
oh, please remove .content and try again

**Comment by kwright5150** [comment]
I did so and I have the same result.

**Comment by webhead404** [comment]
Okay I have done as requested but it still throws the same error.

**Comment by webhead404** [comment]
I'm not sure why this mattered but I went ahead and updated Nessus and now I have scan data.
