### ISSUE TITLE
Nessus CSV files timestamped 5 hours in future.

### ISSUE THREAD

**Issue by Gee94** [HASecuritySolutions/VulnWhisperer#45]
I'm using the standard nessus conf file to pull my scans through but all scans are timestamped 5 hours ahead of their last modified time.

So if i executed a scan at 12pm the CSV file would have a unix time stamp of 5pm on the same day.

Anyone came across a similar issue?

**Comment by austin-taylor** [comment]
What time zone are you in?

**Comment by Gee94** [comment]
GMT

**Comment by Gee94** [comment]
Manually changed time zone in /vulnwhisp/frameworks/nessus.py

**Comment by austin-taylor** [comment]
I'll make it customizable in the config.  Thanks!
