### ISSUE TITLE
Kibana unable to fetch mapping

### ISSUE THREAD

**Issue by webhead404** [HASecuritySolutions/VulnWhisperer#46]
I have placed both filebeat.yml, filebeat input, and nessus logstash config in the correct locations. Logstash doesn't seem to be creating the index. I noticed that there is a logstash template but it isn't clear if it needs to be imported or not.

**Comment by zecchino1** [comment]
Try downloading the tar file for logstash go to the bin directory, run ./logstash -f /etc/logstash/conf.d/1000_nessus_process_file.conf --debug --verbose you will be able to see if it is able to connect.

**Comment by webhead404** [comment]
After running that command the only output I see is 

Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties

even with the verbose argument.

**Comment by webhead404** [comment]
Anyone that can help with this?
