### ISSUE TITLE
Timezone Handling

### ISSUE THREAD

**Issue by harvii** [HASecuritySolutions/VulnWhisperer#49]
Is it necessary to normalize the 'last_modification_date'? wouldn't it be simpler to leave it in UTC and let Kibana handle it?
https://github.com/austin-taylor/VulnWhisperer/blob/e4e9ed7f28b379e1add848441c9448963258e8b6/vulnwhisp/vulnwhisp.py#L257

**Comment by austin-taylor** [comment]
Yeah - this should be removed.  I'll get this updated.

**Comment by reactor7171** [comment]
@austin-taylor I think this [has not been yet changed](https://github.com/austin-taylor/VulnWhisperer/blob/8336b72314597df68560c5ded89aa19490031a3c/vulnwhisp/vulnwhisp.py#L261), is it still something that we want to do?

**Comment by reactor7171** [comment]
Actually, I hadn't notice at the time, but both times are being saved as variables, it can be seen [here](https://github.com/HASecuritySolutions/VulnWhisperer/blob/master/vulnwhisp/vulnwhisp.py#L295), that the variable is the same as the [normalized](https://github.com/HASecuritySolutions/VulnWhisperer/blob/master/vulnwhisp/vulnwhisp.py#L298) one, so I will close this ticket.
