### ISSUE TITLE
Will not pull scans form Nessus

### ISSUE THREAD

**Issue by TheBlindHacker** [HASecuritySolutions/VulnWhisperer#52]
root@scanbox:/opt/vulnwhisperer/configs# cat example.ini 
[nessus]
enabled=true
hostname=192.168.1.54
port=8834
username=scanner
password=!myP@SSWORDisPASSW0RD
write_path=/opt/vulnwhisperer/nessus/
db_path=/opt/vulnwhisperer/database
trash=false
verbose=true

root@sanbox:/bin# vuln_whisperer -c /opt/vulnwhisperer/configs/example.ini -s nessus
[INFO] Creating file /opt/vulnwhisperer/database/report_tracker.db
[INFO] Connected to database at /opt/vulnwhisperer/database/report_tracker.db
[INFO] Attempting to connect to nessus...
[SUCCESS] Connected to nessus on 192.168.1.54:8834
[INFO] Gathering all scan data... this may take a while...
[INFO] Identified 0 scans to be processed
[INFO] No new scans to process. Exiting...

I have over 200 scans on this server

**Comment by tcstool** [comment]
Had the same issue, upgrading to latest build of Nessus solved this for me.

**Comment by reactor7171** [comment]
Seems related even though with another scanner https://github.com/austin-taylor/VulnWhisperer/issues/59.

**Comment by TheBlindHacker** [comment]
solved
