### ISSUE TITLE
Remove InsecureRequestWarning workaround

### ISSUE THREAD

**Issue by tcstool** [HASecuritySolutions/VulnWhisperer#53]
the latest version of requests and urllib3 no longer supports the workaround to remove the insecure requests warning being used.  Execution will fail with the following:

...(snip)...
 from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: cannot import name InsecureRequestWarning

Fixed by removing the imports.  I can push or if you guys just want to fix that's cool too.  Thanks for a great tool!

**Comment by austin-taylor** [comment]
Thank you! Please submit a PR

**Comment by tcstool** [comment]
PR submitted and approved.
