### ISSUE TITLE
Missing dependencies from documentation

### ISSUE THREAD

**Issue by tcstool** [HASecuritySolutions/VulnWhisperer#54]
On Debian 8, the following additional packages must be installed and aren't getting picked up anywhere else:
zlibg1-dev 
Libxml2-dev
Libxslt1-dev

Update docs to reflect.  Again, I can do and push if you want.  Thanks!

**Comment by austin-taylor** [comment]
Yes please submit a PR

**Comment by tcstool** [comment]
PR submitted and approved.
