### ISSUE TITLE
Deprecated Index Mapping

### ISSUE THREAD

**Issue by Skaldenmet** [HASecuritySolutions/VulnWhisperer#56]
Since the given template uses deprecated commands for elasticsearch 6.0+ has someone created a new mapping?

**Comment by gyterpena** [comment]
I use this template for 6.2.2


[EStemplate.txt](https://github.com/austin-taylor/VulnWhisperer/files/2048309/EStemplate.txt)

**Comment by reactor7171** [comment]
Will close this issue in pro of #86 (Support to ELK6). If more people are interested in it, please thumb up the specific issue so that it can be easily followed up.
