### ISSUE TITLE
Kibana crashes when opening dashboards

### ISSUE THREAD

**Issue by Skaldenmet** [HASecuritySolutions/VulnWhisperer#58]
When I open one of your dashboard templates my kibana crashes with the following messages:
```
Version: 6.2.2
Build: 16588
Error: Uncaught TypeError: gaugeTypes[_this.gaugeConfig.type] is not a constructor (http://172.18.48.110/bundles/vendors.bundle.js?v=16588:12)
    at window.onerror (http://172.18.48.110/bundles/commons.bundle.js?v=16588:21:468094)

```

**Comment by austin-taylor** [comment]
What version of ELK are you running

**Comment by austin-taylor** [comment]
Oh, 6.2.2 isn't supported yet.  Still on 5.6.

**Comment by Skaldenmet** [comment]
Oh, ok. May you know a workaround or where to look to get it running on 6.2.2?

**Comment by austin-taylor** [comment]
Planning to work on upgraded version next month.  It shouldn't be too much to convert. Feel free to give it a shot and submit your changes.  Would be a big help
