### ISSUE TITLE
OpenVAS - ERROR: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by ghost** [HASecuritySolutions/VulnWhisperer#66]
Getting the following output when trying to run for OpenVAS:

```
[INFO] Connected to database at /opt/vulnwhisperer/database/report_tracker.db
/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[FAIL] ERROR: ('Connection aborted.', BadStatusLine("''",))
```

I'm unsure of where the issue is occurring. I assume from previous issues that the InsecureRequestWarning" is just that, a warning, and not affecting the login process.

**Comment by Dom1001** [comment]
Please have a look if there is a task with an report in openvas with the username you`ve configured in vulnWhisp. If you use alienvault there are tasks but no reports. Seems Alienvault delete the reports from openvas after adding them in their own db. 
I have, however the same problem on some systems, when I initiate a scan on console with openvasmd. No solution for that atm.

**Comment by reactor7171** [comment]
#123
