### ISSUE TITLE
Limit scans download

### ISSUE THREAD

**Issue by mrnewman** [HASecuritySolutions/VulnWhisperer#80]
So, I've got Qualys VM working.  That's great!
Is there a way to limit where it starts the download process?  I have scans dating back 5+ years and I don't need all that data.  Can the process be set to only pick up scans starting at a particular date?

Thanks!

**Comment by reactor7171** [comment]
Related to https://github.com/austin-taylor/VulnWhisperer/issues/14

**Comment by reactor7171** [comment]
I will close this issue as it is a duplicated from issue #14 as mentioned above. 

I would recommend adding a thumbs up emoji to the issue that you are interested in, as when sorting the issue by thumbs up we will see in a sec which are the most demanded features.
