### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by tcammcom** [HASecuritySolutions/VulnWhisperer#85]
Hello,

Is there going to be an update to the docker-compose file?   It is missing some configuration items in order to build and run.   The documentation goes into how to update the ELK settings if its installed,  but doesn't go into those same configuration for the docker instance. 

Thanks for this project,  it looks great.

**Comment by reactor7171** [comment]
Hi @tcammcom,

I am currently working on a docker-compose file to run out-of-the-box vulnwhisperer with ELK, with just having to specify the config file. Will do a PR with the yaml file once I have it tested and working.

BR,

Quim

**Comment by reactor7171** [comment]
Btw, issue is related to https://github.com/austin-taylor/VulnWhisperer/issues/19, would be great if we could have interesting issues bumped instead of opening new ones :)

Thanks for raising this one up, I also thought it was an important one :)

**Comment by reactor7171** [comment]
Hi @tcammcom ,
Docker-compose is working and there are full instructions to it, you can test it whenever you are able to :)

**Comment by tcammcom** [comment]
Great!  Thanks qmontal.  Will test and get back to you.
