### ISSUE TITLE
[ELK6] Any timeline for ELK6 support available?

### ISSUE THREAD

**Issue by techgourmet** [HASecuritySolutions/VulnWhisperer#86]
Q: Are there plans to bring the Elastic stack to 6.x?
We've recently standardised our environment to 6 and would like to work with VulnWhisperer.

**Comment by austin-taylor** [comment]
Just need to update the logstash configs and visuals for the dashboard. Planning to upgrade after blackhat.

**Comment by creatoni4** [comment]
We are also looking forward to see this....

**Comment by techgourmet** [comment]
Looking forward to it :)

Kind regards,

Roy van der Linden

**Comment by reactor7171** [comment]
Related to #34 and #76. It would be good to keep same requests in a unique issue and work up from there :)

**Comment by reactor7171** [comment]
Will close both #76 and #34 in pro of #86 in order to unify issues that are related to the same. Check #34 regarding Kibana specific comments already made.

**Comment by homa1978** [comment]
Any news when elk 6 is supported?

**Comment by reactor7171** [comment]
@cybergoof is this something that has been solved with https://github.com/HASecuritySolutions/VulnWhisperer/tree/master/kibana/vuln_whisp_kibana_6? Do you think we could close this ticket or not yet?

**Comment by cybergoof** [comment]
No, the vuln_whisp_kibana_6 was specifically for getting Kibana 6.x templates.  What this request needs to build the docker containers to support Elk 6.x.    I was going to work on that this weekend.

**Comment by reactor7171** [comment]
We can consider this done with #145.
