### ISSUE TITLE
VulnWhisperer - Dashboard 'No results found'

### ISSUE THREAD

**Issue by SAFAA-HAZAR** [HASecuritySolutions/VulnWhisperer#87]
Kibana's dashboard shows error 'No result found'  in this section  and render this message error 'Saved "field" parameter is now invalid. Please select a new field.'

1. VulnWhisperer - Critical Assets

And shows empty(white section) in those  sections :

1. VulnWhisperer - Critical Assets Aggregated
2.  VulnWhisperer - TL - TaggedAssetsPluginNames
3. VulnWhisperer - TL - CriticalAssetsPluginNames
4. VulnWhisperer-CVSS
5. VulnWhisperer-CVSSHeatmap

 
![error](https://user-images.githubusercontent.com/25419967/43583453-760efc92-9657-11e8-9f82-0b43f1be0908.PNG)

**Comment by PornCoinVal** [comment]
Same iisue
ELK + FileBeats - >5.6.11
All componets VulnWhisperer compiled without errors and warnings
Logs dowloaded from nessus, configs take from your git branch and corrected ctatlogs
Where we can find?
![image](https://user-images.githubusercontent.com/29483776/45445614-5a0dab00-b6d3-11e8-8193-dfaa19bfe8fb.png)

**Comment by reactor7171** [comment]
Hi @SAFAA-HAZAR ,

The PR https://github.com/austin-taylor/VulnWhisperer/pull/95 has fixed the message error you were mentioning `Saved "field" parameter is now invalid. Please select a new field.`

Regarding the Kibana dashboards not showing any results, have you made sure that Kibana's `time picker` is selecting the range in which your data was created? By default, Kibana shows the last 15 minutes only, usually not matching with any data.

Cheers!
