### ISSUE TITLE
Upgrade qualysapi dependency

### ISSUE THREAD

**Issue by reactor7171** [HASecuritySolutions/VulnWhisperer#99]
We are using an old qualysapi dependency, which is working with the VulnWhisperer project unlike the latest version of qualysapi, but it creates an extra dependency on the project, needing to add the code of the library to the project in order to not depend on another external dependency.

The latest version of qualysapi when downloading directly with pip is qualysapi-5.0.3, it would be good to update both Qualys Web Scanner and Qualys Vulnerability Management modules to work with that dependency and avoid maintaining our own version of the dependency.

Related to #51. Mention to @kraigu :)

**Comment by kraigu** [comment]
Hah, thanks. :) Parag's been active lately so pull requests to him may help. I can't promise to be of much help myself, it's busy here nowadays.

**Comment by reactor7171** [comment]
This is already fixed in the testing environment, will merge with master once we have the new version of qualysapi in pip updated.
